targets:
  - target: "sleep.target"
    dlib: "bin/sleep.so"
    toggle: true
    start: true
    system: false
    dbus:
      path: "/org/freedesktop/login1"
      interface: "org.freedesktop.login1.Manager"
      member: "PrepareForSleep"

  - target: "lock.target"
    dlib: "bin/lock.so"
    toggle: false
    start: true
    system: false
    dbus:
      interface: "org.freedesktop.login1.Session"
      sender: "org.freedesktop.login1"
      member: "Lock"
      
  - target: "unlock.target"
    dlib: "bin/lock.so"
    toggle: false
    start: true
    system: false
    dbus:
      interface: "org.freedesktop.login1.Session"
      sender: "org.freedesktop.login1"
      member: "Unlock"
